name: CI Microserviços

on: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adoptopenjdk'

      - name: Build dos serviços Spring Boot
        run: |
          cd authentication && ./mvn clean install && cd .. 
          cd morada-do-sol && ./mvn clean install && cd .. 
          cd ms_servicos && ./mvn clean install && cd ..
          cd ms-morador && ./mvn clean install && cd ..

      - name:  Instalar dependencias do frontend
        run: |
          cd condominio-morada-sol
          npm install
          npm run build